### ISSUE TITLE
Move test data files to separate repo

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/satmeta#1]
The repo is quite large due to the test data files.

We should move those to a separate repo (be sure to use git large-file support) and require it only for running the tests, like e.g. `modis_atm[_data]` or `bathymetry[_testdata]` do it.

**Comment by dionhaefner** [comment]
We could also leave these files in the repo, and register them with git LFS?

**Comment by j08lue** [comment]
Does that mean they are not always downloaded when cloning the repo?

**Comment by dionhaefner** [comment]
It depends. First of all, you need to have git LFS installed (which most people don't I suppose). And there are options you can set globally, maybe even on a per-repo basis (I saw people mentioning `git lfs install --local`).

**Comment by j08lue** [comment]
I just did a test. With standard git LFS install, all the files are pulled. I think it is the indexing and version control that is optimized for these files.
```
λ  git clone https://github.com/DHI-GRAS/modis_atm_data
Cloning into 'modis_atm_data'...
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15 (delta 0), reused 11 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
Downloading modis_atm_data/MOD04_3K.A2017001.1155.006.2017009173648.hdf (6.6 MB)
Downloading modis_atm_data/MOD05_L2.A2017001.1155.006.2017009173340.hdf (5.0 MB)
Downloading modis_atm_data/MOD07_L2.A2017001.1155.006.2017004142736.hdf (5.4 MB)
```

**Comment by j08lue** [comment]
Won't fix this. Keeping files in the repo is just so much simpler. Might consider zipping them.
