### ISSUE TITLE
Provide a way to get raw S2 angles

### ISSUE THREAD

**Issue by dionhaefner** [DHI-GRAS/satmeta#17]
I would like to extract raw, non-resampled viewing angles from a Sentinel 2 meta data file. I would like to do so without constructing a `transform` or anything. Is there a way to do this?

**Comment by j08lue** [comment]
`satmeta.s2.angles_2d.parse_angles` does that.

**Comment by j08lue** [comment]
> raw

In the metadata file, the viewing angles field is split up into several slices, one per detector, that I merge in [`_get_values_merged_detectors`](https://github.com/DHI-GRAS/satmeta/blob/be504e40c0932367a108aa4a2f58b55bb172c167/satmeta/s2/angles_2d.py#L52). So `parse_angles` does not give the very raw data.

**Comment by dionhaefner** [comment]
Thanks!
